### ISSUE TITLE
'holocron build -c path/to/conf' read paths relative to current dir, not to conf

### ISSUE THREAD

**Issue by ikalnitsky** [ikalnitsky/holocron#108]
For instance, I have the following `_config.yml`:

```yaml
paths:
   content: '.'
   output: '_build'
   theme: '_theme'
```

The paths above will be considered as relative to current working directory and that's wrong, because the

```
$ holocron build --conf path/to/_config.yml
```

will try to build entire current directory, not the directory with `_config.yml`.
