### ISSUE TITLE
Holocron extensions must be able to set up new base theme

### ISSUE THREAD

**Issue by ikalnitsky** [ikalnitsky/holocron#171]
Holocron extensions must be able to setup new base theme, so the whole workflow will look like:

1. Install extension with theme

   ```bash
   $ (sudo) pip install holocron-my-awesome-theme
   ```

2. Activate theme in `_config.yml`

   ```yaml
   ext:
     enabled:
       - ...
       - my-awesome-theme
       - ...
   ```
