### ISSUE TITLE
Default theme should support Fork on GitHub label

### ISSUE THREAD

**Issue by ikalnitsky** [ikalnitsky/holocron#37]

**Comment by ikalnitsky** [comment]
Default theme will support an abstract ribbon (label). In order to enable it user should use a special theme option - `ribbon`:

```yaml
theme:
   ribbon:
      text: text to be shown
      link: link to be visited
```
